### PR TITLE
Ensure the timestamps that are returned correspond to the requested range

### PR DESCRIPTION
**Pull request by poy**
Also, only request GAUGE, COUNTER and TIMER types for PromQL requests.

### CODE REVIEW

**Comment by toddboom** [comment]
@apoydence Thanks for catching the issue in #89!

I think the envelope type issue was resolved in 926fa3c654caf1c9f8257029d67653b48f78a873.

Regarding the timestamp change, I think there was desire to preserve the envelope's original timestamp, so modifying it directly is something we'd like to avoid if possible. We'll take a look at the walk algorithm to see if there's a way we can avoid getting it stuck in the request loop.

**Comment by poy** [comment]
@toddboom I don't think the problem is in the Walk algorithm. I think it is exposing it. If the request asks for a time range, it seems invalid to give anything outside of that range.

**Comment by toddboom** [comment]
@apoydence Fair point. Seems like it mike the most make sense to drop those points from the response then. We'll take a look at that now and try to get the fix in for 1.4.5.

**Comment by poy** [comment]
@toddboom If you don't include those points, then does that remove the need to "fudge" the timstamps. Essentially that is removing the need for the hash collision resolution and going back to just taking the last envelope with the given timestamp.

**Comment by toddboom** [comment]
@apoydence I think we've come up with a solution that will solve this in the Store. We'll push it up to master before the end of the day, so I'm going to close this out.

**Comment by poy** [comment]
@toddboom I only now looked into your comment saying:

> I think the envelope type issue was resolved in 926fa3c. 

This seems wrong still. The PromQL client is still asking for all envelope types (including Logs), and will therefore have a large cost as those envelopes are marshaled and transported. This also includes the extra query calls the `Walk` algorithm will have to do as it goes and fetches more times.

**Pull request closed without merging**
